### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by silverwind** [mcler/postcss-discard-overridden-props#1]
This looks like a useful plugin but it seems it's not on npm yet. Would you mind publishing it?

**Comment by MarkRosemaker** [comment]
Seconded! Please. :)

**Comment by mcler** [comment]
@silverwind @MarkRosemaker

Sorry for delay, I did not notice your messages. I stopped developing this plugin for several reasons:
- You actually can install Github repo as package without NPM
- It uses an outdated `PostCSS` version and needs rewriting, new tests and support for new syntax
- I do not see strong need in it because minifiers like `cssnano` do the same job as well
- There is fresh fork https://github.com/simondud/postcss-discard-overridden-props of my repo published to NPM (twice) and may be it will help you
